"""Initial revision

Revision ID: 01293294c51c
Revises: 
Create Date: 2025-03-27 22:21:04.726245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01293294c51c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TEAMS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('minimalMembers', sa.Integer(), nullable=False),
    sa.Column('maximalMembers', sa.Integer(), nullable=False),
    sa.Column('enableCrews', sa.Boolean(), nullable=False),
    sa.Column('minimalCrews', sa.Integer(), nullable=False),
    sa.Column('maximalCrews', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('suspendRecruitment', sa.Boolean(), nullable=False),
    sa.Column('suspendPendingQueue', sa.Boolean(), nullable=False),
    sa.Column('suspendDeadlineQueue', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('ADMINS',
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['TEAMS.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'userName', 'teamId')
    )
    op.create_table('CREWS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('minimalMates', sa.Integer(), nullable=False),
    sa.Column('maximalMates', sa.Integer(), nullable=False),
    sa.Column('special', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['TEAMS.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teamId', 'title', 'special')
    )
    op.create_table('OUTCASTS',
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['TEAMS.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'userName', 'teamId')
    )
    op.create_table('LEADERS',
    sa.Column('crewId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crewId'], ['CREWS.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'userName', 'crewId')
    )
    op.create_table('MEMBERS',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('crewId', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crewId'], ['CREWS.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teamId'], ['TEAMS.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'number', 'teamId'),
    sa.UniqueConstraint('userName', 'number', 'teamId', 'position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MEMBERS')
    op.drop_table('LEADERS')
    op.drop_table('OUTCASTS')
    op.drop_table('CREWS')
    op.drop_table('ADMINS')
    op.drop_table('TEAMS')
    # ### end Alembic commands ###
