"""Nullable maximal crews.

Revision ID: 28bdce75ac12
Revises: aee119771981
Create Date: 2025-06-28 19:53:40.263420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28bdce75ac12'
down_revision: Union[str, None] = 'aee119771981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TEAMS', schema=None) as batch_op:
        batch_op.alter_column('maximalCrews',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TEAMS', schema=None) as batch_op:
        batch_op.alter_column('maximalCrews',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
