"""Update constraints 3

Revision ID: 68da3241551b
Revises: f579e41f3339
Create Date: 2025-04-12 14:17:31.663518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68da3241551b'
down_revision: Union[str, None] = 'f579e41f3339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MEMBERS', schema=None) as batch_op:
        batch_op.create_unique_constraint('UniqueMember', ['userId', 'userName', 'number', 'teamId', 'position'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MEMBERS', schema=None) as batch_op:
        batch_op.drop_constraint('UniqueMember', type_='unique')

    # ### end Alembic commands ###
