"""Initial revision

Revision ID: 777cefde1ab2
Revises: 
Create Date: 2025-03-22 11:15:25.669734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777cefde1ab2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('<built-in method upper of str object at 0x7f051a3c3de0>S',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('minimalMembers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('maximalMembers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enableCrews', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('restrictCrews', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('minimalCrews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('maximalCrews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enableDeadline', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deadline', sa.DateTime(), server_default='NULL', nullable=True),
    sa.Column('suspendRecruitment', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('suspendPendingQueue', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('suspendDeadlineQueue', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('<built-in method upper of str object at 0x7f051a3fe670>S',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('minimalMates', sa.Integer(), server_default='0', nullable=False),
    sa.Column('maximalMates', sa.Integer(), server_default='0', nullable=False),
    sa.Column('special', sa.Integer(), server_default='0', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['<built-in method upper of str object at 0x7f051a3c3de0>S.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teamId', 'title', 'special')
    )
    op.create_table('<built-in method upper of str object at 0x7f051a40ced0>S',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['<built-in method upper of str object at 0x7f051a3c3de0>S.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'teamId')
    )
    op.create_table('<built-in method upper of str object at 0x7f051a3ffc00>S',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('crewId', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crewId'], ['<built-in method upper of str object at 0x7f051a3fe670>S.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teamId'], ['<built-in method upper of str object at 0x7f051a3c3de0>S.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'number', 'teamId'),
    sa.UniqueConstraint('userId', 'number', 'teamId', 'position')
    )
    op.create_table('<built-in method upper of str object at 0x7f051a40d650>S',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('crewId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crewId'], ['<built-in method upper of str object at 0x7f051a3fe670>S.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'crewId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('<built-in method upper of str object at 0x7f051a40d650>S')
    op.drop_table('<built-in method upper of str object at 0x7f051a3ffc00>S')
    op.drop_table('<built-in method upper of str object at 0x7f051a40ced0>S')
    op.drop_table('<built-in method upper of str object at 0x7f051a3fe670>S')
    op.drop_table('<built-in method upper of str object at 0x7f051a3c3de0>S')
    # ### end Alembic commands ###
