"""Tables was renamed

Revision ID: a02440b1ef24
Revises: 777cefde1ab2
Create Date: 2025-03-22 14:08:49.725128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02440b1ef24'
down_revision: Union[str, None] = '777cefde1ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TEAMS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('minimalMembers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('maximalMembers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enableCrews', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('restrictCrews', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('minimalCrews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('maximalCrews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enableDeadline', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deadline', sa.DateTime(), server_default='NULL', nullable=True),
    sa.Column('suspendRecruitment', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('suspendPendingQueue', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('suspendDeadlineQueue', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('ADMINS',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['TEAMS.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'teamId')
    )
    op.create_table('CREWS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('minimalMates', sa.Integer(), server_default='0', nullable=False),
    sa.Column('maximalMates', sa.Integer(), server_default='0', nullable=False),
    sa.Column('special', sa.Integer(), server_default='0', nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['TEAMS.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teamId', 'title', 'special')
    )
    op.create_table('LEADERS',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('crewId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crewId'], ['CREWS.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'crewId')
    )
    op.create_table('MEMBERS',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('crewId', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crewId'], ['CREWS.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teamId'], ['TEAMS.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'number', 'teamId'),
    sa.UniqueConstraint('userId', 'number', 'teamId', 'position')
    )
    op.drop_table('<built-in method upper of str object at 0x7f051a3ffc00>S')
    op.drop_table('<built-in method upper of str object at 0x7f051a40ced0>S')
    op.drop_table('<built-in method upper of str object at 0x7f051a40d650>S')
    op.drop_table('<built-in method upper of str object at 0x7f051a3fe670>S')
    op.drop_table('<built-in method upper of str object at 0x7f051a3c3de0>S')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('<built-in method upper of str object at 0x7f051a3c3de0>S',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), server_default=sa.text("('')"), nullable=False),
    sa.Column('minimalMembers', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('maximalMembers', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('enableCrews', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('restrictCrews', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('minimalCrews', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('maximalCrews', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('enableDeadline', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('deadline', sa.DATETIME(), server_default=sa.text("'NULL'"), nullable=True),
    sa.Column('suspendRecruitment', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('suspendPendingQueue', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('suspendDeadlineQueue', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('<built-in method upper of str object at 0x7f051a3fe670>S',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('teamId', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('minimalMates', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('maximalMates', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('special', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['<built-in method upper of str object at 0x7f051a3c3de0>S.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teamId', 'title', 'special')
    )
    op.create_table('<built-in method upper of str object at 0x7f051a40d650>S',
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('crewId', sa.INTEGER(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crewId'], ['<built-in method upper of str object at 0x7f051a3fe670>S.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'crewId')
    )
    op.create_table('<built-in method upper of str object at 0x7f051a40ced0>S',
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('teamId', sa.INTEGER(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['<built-in method upper of str object at 0x7f051a3c3de0>S.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'teamId')
    )
    op.create_table('<built-in method upper of str object at 0x7f051a3ffc00>S',
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('teamId', sa.INTEGER(), nullable=False),
    sa.Column('crewId', sa.INTEGER(), nullable=True),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crewId'], ['<built-in method upper of str object at 0x7f051a3fe670>S.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teamId'], ['<built-in method upper of str object at 0x7f051a3c3de0>S.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'number', 'teamId'),
    sa.UniqueConstraint('userId', 'number', 'teamId', 'position')
    )
    op.drop_table('MEMBERS')
    op.drop_table('LEADERS')
    op.drop_table('CREWS')
    op.drop_table('ADMINS')
    op.drop_table('TEAMS')
    # ### end Alembic commands ###
