"""Remove suspend pending and remane suspend deadline.

Revision ID: ab08dd51994d
Revises: 68da3241551b
Create Date: 2025-06-28 14:00:42.458071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab08dd51994d'
down_revision: Union[str, None] = '68da3241551b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_TEAMS')
    with op.batch_alter_table('TEAMS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspendOnDeadline', sa.Boolean(), server_default='0', nullable=False))
        batch_op.drop_column('suspendDeadlineQueue')
        batch_op.drop_column('suspendPendingQueue')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TEAMS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspendPendingQueue', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('suspendDeadlineQueue', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('suspendOnDeadline')

    op.create_table('_alembic_tmp_TEAMS',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('minimalMembers', sa.INTEGER(), nullable=False),
    sa.Column('maximalMembers', sa.INTEGER(), nullable=False),
    sa.Column('enableCrews', sa.BOOLEAN(), nullable=False),
    sa.Column('minimalCrews', sa.INTEGER(), nullable=False),
    sa.Column('maximalCrews', sa.INTEGER(), nullable=False),
    sa.Column('deadline', sa.DATETIME(), nullable=True),
    sa.Column('suspendRecruitment', sa.BOOLEAN(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('suspendCompanions', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('suspendOnDeadline', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###
