"""Nullable maximal.

Revision ID: aee119771981
Revises: ab08dd51994d
Create Date: 2025-06-28 19:32:42.107530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee119771981'
down_revision: Union[str, None] = 'ab08dd51994d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CREWS', schema=None) as batch_op:
        batch_op.alter_column('maximalMates',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('TEAMS', schema=None) as batch_op:
        batch_op.alter_column('maximalMembers',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TEAMS', schema=None) as batch_op:
        batch_op.alter_column('maximalMembers',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('CREWS', schema=None) as batch_op:
        batch_op.alter_column('maximalMates',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
