"""Add the position to a crew.

Revision ID: d21b00237adf
Revises: 28bdce75ac12
Create Date: 2025-06-29 13:04:04.960577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21b00237adf'
down_revision: Union[str, None] = '28bdce75ac12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CREWS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CREWS', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
