"""Add suspendCompanions team column

Revision ID: f579e41f3339
Revises: a0e0fb86bcdb
Create Date: 2025-04-12 13:52:14.176133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f579e41f3339'
down_revision: Union[str, None] = 'a0e0fb86bcdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TEAMS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspendCompanions', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TEAMS', schema=None) as batch_op:
        batch_op.drop_column('suspendCompanions')

    # ### end Alembic commands ###
